### PR TITLE
Added CSSE2310 Calculations

### PR DESCRIPTION
**Pull request by WilliamHayward**
Part of #2 , this adds the CSSE2310 calculations for
* Total score
* Total dropped
* Required final grade

It's a little bit messy at a few points, namely that 

1.  It determines which assessment items are part of the assignment mark by checking which ones have a 25% weighting. Ditto with midsem.
2. Because of #15 , it uses a switch statement to determine if the course is CSSE2310.

But the actual logic is solid, it's worked on every scenario I've tried it on.

Oh, it also adds the course code to the spec, which was previously not happening resulting in self.code being undefined.

### CODE REVIEW

**Comment by gricey432** [comment]
I'm going to close this. The code has massive conflicts but more importantly I'm against the idea of hardcoding anything into the client. This won't work for any given semester if the assessment criteria changes.

**Comment by WilliamHayward** [comment]
:+1: 

The merge conflicts were just unfortunate timing I think, I submitted this before pulling some of the more recent changes.

Is there any plan for how to handle CSSE2310/other non-standard subjects if not by hard-coding?

**Comment by WilliamHayward** [comment]
Was there a history rewrite for this repo, actually? I can't find any of the commits immediately prior to mine in the history (8b26e6b, 1951f21, etc)

**Comment by gricey432** [comment]
Yeah, I made some really bad choices on master and then rewrote history. I decided to migrate the whole thing to the dynamodb style and then regretted it, so I retroactively moved all those commits to a branch.

**Pull request closed without merging**
