### PR TITLE
Preparation for Semester 1, 2017.

### PR DESCRIPTION
**Pull request by ruchern**
Signed-off-by: Ru Chern Chong <me@ruchern.com>

### CODE REVIEW

**Comment by gricey432** [comment]
Thanks, I'll merge and run this soon, just still a surprising number of courses with no course profiles yet

**Comment by ruchern** [comment]
I am very surprised that rota hasn't release a single thing for Sem 1, 2017.

**Comment by gricey432** [comment]
Rota is maintained by ITEE, not software services afaik. Chances are whoever was maintaining it, isn't maintaining it anymore.

**Comment by gricey432** [comment]
Though I appreciate the PR, I finally made it DB powered and this is no longer relevant.

**Comment by ruchern** [comment]
Regarding #1 ? Yup I saw that. Good to see that now.

**Pull request closed without merging**
